### ISSUE TITLE
Adding Simple Non-linear Transformation Features to Analysis

### ISSUE THREAD

**Issue by abarendregt** [jdzak/bike-sharing-demand#4]
I believe that in this game, the one with the most options wins.  For Non-linear relationships, using transformations will allow us to quickly see the benifits / costs of our data set.  We need a feature that will analyze our data set using the different transformation models described here:

http://stattrek.com/regression/linear-transformation.aspx

**Comment by abarendregt** [comment]
Right now 'y' is defined as a m x 1 matrix ('m' rows by 1 column).  As far as keeping everything organized goes, I believe that most of the transforms can be achieved by performing that operation in a new column.  For example, column 2 of the y value can be [y2]=log([y1]) and column 3 can be [y3]=sqrt(y1) etc.  

Let me know if this organizes things to your liking.

**Comment by abarendregt** [comment]
Added "transformFeatures.m" file.  If you approve it John, this issue is closed.

**Comment by jdzak** [comment]
Alan has this working
